# -*- coding: utf-8 -*-
"""Loading-Displaying_Images.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYASriFUpCY9zZP28L2bGN77j1r5_arQ
"""

# Commented out IPython magic to ensure Python compatibility.
!wget https://pyimagesearch-code-downloads.s3-us-west-2.amazonaws.com/opencv-load-image.zip
!unzip -qq opencv-load-image.zip
# %cd opencv-load-image

# import the necessary packages
from matplotlib import pyplot as plt
import argparse
import cv2

def plt_imshow(title, image):
	# convert the image frame BGR to RGB color space and display it
	image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
	plt.imshow(image)
	plt.title(title)
	plt.grid(False)
	plt.show()

args = {
	"image": "30th_birthday.png",
}

image = cv2.imread(args["image"])
(h, w, c) = image.shape[:3]

print("width: {} pixels".format(image.shape[1]))
print("height: {}  pixels".format(image.shape[0]))
print("channels: {}".format(image.shape[2]))

# show the image and wait for a keypress
plt_imshow("Image", image)

# save the image back to disk (OpenCV handles converting image
# filetypes automatically)
cv2.imwrite("newimage.jpg", image)